countries_dict = {
  'TH': ['Thailand', 2, 3],
  'OM': ['Oman', 4, 9],
  'CN': ['South China Sea Islands (disputed)', 1, 1],
  'NL': ['The Netherlands', 1, 1],
  'MA': ['Morocco', 2, 2],
  'ES': ['Spain', 8, 8],
  'MX': ['Mexico', 1, 2],
  'MC': ['Monaco', 1, 1],
  'BR': ['Brazil', 2, 2],
  'GB': ['United Kingdom', 2, 2],
  'GR': ['Greece', 29, 34],
  'PT': ['Portugal', 13, 17],
  'AG': ['Antigua and Barbuda', 1, 1],
  'CA': ['Canada', 2, 2],
  'FR': ['France', 9, 11],
  'AT': ['Austria', 19, 23],
  'TZ': ['Tanzania', 5, 5],
  'US': ['United States of America', 15, 15],
  'MT': ['Malta', 5, 6],
  'IT': ['Italy', 13, 15],
  'HU': ['Hungary', 1, 1],
  'TR': ['Turkey', 3, 5],
  'CH': ['Switzerland', 1, 1],
  'DZ': ['Algeria', 1, 1]
}
