countries_dict = {
  'GB': ['United Kingdom', 3, 7],
  'IL': ['Israel', 4, 6],
  'CN': ['South China Sea Islands (disputed)', 3, 10],
  'RU': ['Russia', 35, 81],
  'VN': ['Vietnam', 5, 18],
  'TR': ['Turkey', 3, 8],
  'MA': ['Morocco', 4, 7],
  'MC': ['Monaco', 1, 1],
  'GR': ['Greece', 6, 9],
  'NO': ['Norway', 6, 11],
  'MX': ['Mexico', 2, 5],
  'ES': ['Spain', 12, 24],
  'EG': ['Egypt', 1, 1],
  'HU': ['Hungary', 2, 3],
  'MY': ['Malaysia', 3, 14],
  'TH': ['Thailand', 16, 34],
  'IT': ['Italy', 10, 28],
  'AZ': ['Azerbaijan', 4, 5],
  'CU': ['Cuba', 12, 24],
  'AR': ['Argentina', 1, 2],
  'VA': ['Vatican City', 1, 3],
  'CY': ['Cyprus', 1, 4],
  'NL': ['The Netherlands', 1, 1],
  'AT': ['Austria', 1, 1],
  'AE': ['United Arab Emirates', 4, 6],
  'PT': ['Portugal', 3, 5],
  'SE': ['Sweden', 3, 4],
  'BR': ['Brazil', 4, 14],
  'HR': ['Croatia', 2, 2],
  'FI': ['Finland', 1, 1],
  'FR': ['France', 3, 10],
  'UZ': ['Uzbekistan', 5, 11]
}
