countries_dict = {
  'DE': ['Germany', 11, 12],
  'ZA': ['South Africa', 9, 12],
  'GR': ['Greece', 1, 1],
  'IL': ['Israel', 1, 1],
  'MY': ['Malaysia', 1, 1],
  'FR': ['France', 11, 11],
  'UA': ['Ukraine', 1, 1],
  'ES': ['Spain', 1, 1],
  'AT': ['Austria', 1, 1],
  'CH': ['Switzerland', 4, 4],
  'BE': ['Belgium', 102, 117],
  'MC': ['Monaco', 1, 1],
  'IN': ['India', 1, 1],
  'DK': ['Denmark', 1, 1],
  'CI': ["Côte d'Ivoire", 1, 1],
  'KR': ['South Korea', 2, 2],
  'GB': ['United Kingdom', 2, 2],
  'RU': ['Russia', 1, 1],
  'TR': ['Turkey', 1, 1],
  'JP': ['Japan', 1, 1],
  'HU': ['Hungary', 1, 1],
  'NL': ['Netherlands', 7, 7],
  'CN': ['South China Sea Islands (disputed)', 1, 1],
  'VA': ['Vatican City', 1, 1],
  'PL': ['Poland', 5, 6],
  'US': ['United States of America', 8, 8],
  'PT': ['Portugal', 1, 1],
  'IT': ['Italy', 1, 1]
}
