countries_dict = {
  'CU': ['Cuba', 5, 6],
  'PK': ['Pakistan', 1, 1],
  'MY': ['Malaysia', 1, 1],
  'SE': ['Sweden', 4, 5],
  'GB': ['United Kingdom', 1949, 2174],
  'IT': ['Italy', 31, 31],
  'AG': ['Antigua and Barbuda', 3, 3],
  'HT': ['Haiti', 5, 7],
  'FR': ['France', 25, 29],
  'SG': ['Singapore', 14, 22],
  'AE': ['United Arab Emirates', 4, 4],
  'MT': ['Malta', 40, 41],
  'IN': ['India', 9, 9],
  'MX': ['Mexico', 110, 125],
  'EE': ['Estonia', 1, 2],
  'BB': ['Barbados', 4, 4],
  'BS': ['Bahamas', 9, 10],
  'BE': ['Belgium', 2, 2],
  'US': ['United States of America', 72, 79],
  'HR': ['Croatia', 15, 15],
  'NL': ['The Netherlands', 3, 3],
  'GG': ['Guernsey', 5, 6],
  'GR': ['Greece', 28, 29],
  'ES': ['Spain', 41, 48],
  'LC': ['Saint Lucia', 3, 4],
  'HN': ['Honduras', 4, 6],
  'VC': ['Saint Vincent and the Grenadines', 1, 1],
  'OM': ['Oman', 3, 3],
  'PT': ['Portugal', 4, 4],
  'NO': ['Norway', 1, 1],
  'MA': ['Morocco', 1, 1]
}
