countries_dict = {
  'UG': ['Uganda', 1, 1],
  'GB': ['United Kingdom', 29, 30],
  'ES': ['Spain', 1, 1],
  'TO': ['Tonga', 7, 7],
  'ID': ['Indonesia', 33, 34],
  'DK': ['Denmark', 9, 9],
  'FI': ['Finland', 8, 8],
  'TL': ['East Timor', 1, 1],
  'PL': ['Poland', 40, 42],
  'OM': ['Oman', 2, 2],
  'CN': ['South China Sea Islands (disputed)', 3, 3],
  'KE': ['Kenya', 1, 1],
  'KR': ['South Korea', 3, 3],
  'BI': ['Burundi', 9, 9],
  'ZM': ['Zambia', 1, 1],
  'BE': ['Belgium', 31, 34],
  'SG': ['Singapore', 13, 15],
  'DE': ['Germany', 91, 96],
  'NZ': ['New Zealand', 28, 28],
  'IE': ['Ireland', 25, 26],
  'NL': ['Netherlands', 26, 26],
  'PK': ['Pakistan', 4, 4],
  'SE': ['Sweden', 3, 3],
  'AE': ['United Arab Emirates', 1, 1],
  'GL': ['Greenland', 2, 2],
  'FJ': ['Fiji', 1, 1],
  'CK': ['Cook Islands', 3, 3],
  'AU': ['Australia', 381, 404],
  'US': ['United States of America', 11, 11],
  'VU': ['Vanuatu', 8, 8],
  'ZA': ['South Africa', 1, 1],
  'TR': ['Turkey', 65, 74],
  'SB': ['Solomon Islands', 34, 37],
  'CA': ['Canada', 1, 1]
}
