countries_dict = {
  'BS': ['Bahamas', 1, 1],
  'CM': ['Cameroon', 1, 1],
  'EG': ['Egypt', 1, 1],
  'TN': ['Tunisia', 2, 2],
  'FR': ['France', 10, 13],
  'SA': ['Saudi Arabia', 1, 1],
  'IN': ['India', 5, 727],
  'GR': ['Greece', 129, 176],
  'SD': ['Sudan', 2, 2],
  'GG': ['Guernsey', 1, 1],
  'NO': ['Norway', 1, 1],
  'BE': ['Belgium', 2, 3],
  'AD': ['Andorra', 1, 1],
  'GE': ['Georgia', 1, 1],
  'NL': ['Netherlands', 2, 2],
  'DE': ['Germany', 6, 6],
  'ES': ['Spain', 7, 9],
  'TH': ['Thailand', 2, 3],
  'AM': ['Armenia', 1, 1],
  'KI': ['Kiribati', 3, 3],
  'JP': ['Japan', 2, 2],
  'BR': ['Brazil', 4, 6],
  'CH': ['Switzerland', 2, 3],
  'GA': ['Gabon', 1, 1],
  'IE': ['Ireland', 1, 1],
  'CN': ['South China Sea Islands (disputed)', 1, 1],
  'JE': ['Jersey', 1, 1],
  'RS': ['Serbia', 1, 1],
  'LB': ['Lebanon', 4, 4],
  'GL': ['Greenland', 1, 1],
  'DK': ['Denmark', 1, 1],
  'CZ': ['Czechia', 1, 1],
  'IT': ['Italy', 11, 13],
  'RU': ['Russia', 1, 1],
  'US': ['United States of America', 41, 48],
  'JO': ['Jordan', 1, 1],
  'GB': ['United Kingdom', 7, 13],
  'HU': ['Hungary', 1, 1]
}
