countries_dict = {
  'KE': ['Kenya', 73, 83],
  'GB': ['United Kingdom', 15, 15],
  'NL': ['Netherlands', 13, 16],
  'FR': ['France', 124, 147],
  'MA': ['Morocco', 6, 6],
  'DO': ['Dominican Republic', 1, 1],
  'US': ['United States of America', 15, 16],
  'GE': ['Georgia', 15, 15],
  'VA': ['Vatican City', 2, 2],
  'CA': ['Canada', 1, 1],
  'PT': ['Portugal', 5, 5],
  'SE': ['Sweden', 6, 8],
  'BE': ['Belgium', 2, 2],
  'EG': ['Egypt', 6, 7],
  'ES': ['Spain', 7, 8],
  'GR': ['Greece', 16, 16],
  'CN': ['South China Sea Islands (disputed)', 19, 20],
  'IT': ['Italy', 13, 15]
}
