countries_dict = {
  'CN': ['South China Sea Islands (disputed)', 1, 1],
  'NZ': ['New Zealand', 1, 1],
  'CA': ['Canada', 928, 1810],
  'ET': ['Ethiopia', 1, 1],
  'GB': ['United Kingdom', 18, 22],
  'AU': ['Australia', 1, 1],
  'MN': ['Mongolia', 1, 2],
  'NA': ['Namibia', 1, 1],
  'TW': ['Taiwan', 1, 1],
  'DE': ['Germany', 2, 3],
  'IT': ['Italy', 35, 43],
  'QA': ['Qatar', 1, 1],
  'CU': ['Cuba', 86, 166],
  'FR': ['France', 10, 14],
  'US': ['United States', 84, 149],
  'CD': ['Democratic Republic of the Congo', 1, 1],
  'ID': ['Indonesia', 1, 1],
  'LY': ['Libya', 1, 1]
}
